export const MODELS = [
    'R 15 S',
    'Sportster 883',
    'FZ',
    'Classic 350',
    'Pulsar 150',
    'Dio',
    'Pulsar 200',
    'Maestro',
    'Discover 125',
    'Dominor',
    'Hf Deluxe',
    'RC 200',
    'Access 125',
    'Ninja Z 1000',
    'Ninja ZX 10 R ',
    'TNT 300',
    'Activa',
    'Shine',
    'Classic 500',
    'Unicorn 160',
    'Fascino',
    'Passion Plus',
    'Pulsar 135',
    'CB Hornet',
    'Apache RTR 160',
    'Avenger 220 Street',
    'Centuro',
    'SZ RR',
    'Mastero Edge',
    'Glamour i3s',
    'Duet'
];
/* Line number -2 is the model id*/