export const MODELS = [
    'R 15 S',
    'Sportster 883',
    'FZ 25',
    'Classic 350',
    'Pulsar 150',
    'Dio',
    'Pulsar 200',
    'Maestro',
    'Discover 125',
    'Dominor',
    'Hf Deluxe',
    'RC 200',
    'Access 125',
    'Ninja Z 1000',
    'Ninja ZX 10 R ',
    'TNT 300',
    'Activa',
    'Shine',
    'Classic 500',
    'Unicorn 160',
    'Fascino',
    'Passion Plus',
    'Pulsar 135',
    'CB Hornet',
    'Apache RTR 160',
    'Avenger 220 Street',
    'Centuro',
    'SZ RR',
    'Mastero Edge',
    'Glamour i3s',
    'Duet',
    'Pulsar AS 150',
    'Pulsar 180',
    'Unicorn 150',
    'Apache 180',
    'Pulsar 200 NS',
    'Pulsar 220 F',
    'Dominar 400',
    'Duke 125',
    'CBR 150',
    'CBR 250',
    'Fazer 25',
    'Triumph',
    'BMW Motorcycle',
    'Benelli',
    'Kawasaki',
    'CBR 1000R',
    'CBR 650F',
    'CRF 1000L',
    'Ducati',
    'Hyousung',
    'HF Dawn',
    'Yamaha FZ V3',
    'Apache 200',
    'Yamaha Ray ZR',
    'Yamaha FZ',
    'FZ V3',
    'Ray ZR',
    'FZ',    
];
/* Line number -2 is the model id*/