export const BRANDS = [
    'Yamaha',
    'Harley Davidson', 
    'Royal Enfield', 
    'Bajaj',
    'Honda',
    'Hero', 
    'KTM',
    'Suzuki',
    'Kawasaki',
    'Benelli',
    'TVS',
    'Mahindra',
    'Triumph',
    'Ducati',
    'Piaggio',
    'BMW',
    'Hyosung',
    'UM',
    'Jawa',
];