export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const VEHICLE_LIST = 'VEHICLE_LIST';

export const API_FAIL = 'API_FAIL';
export const GET_PAGINATED_VEHICLES = 'GET_PAGINATED_VEHICLES';
export const GET_VEHICLE_DATA = 'GET_VEHICLE_DATA';