export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const VEHICLE_LIST = 'VEHICLE_LIST';

export const API_FAIL = 'API_FAIL';
export const GET_PAGINATED_VEHICLES = 'GET_PAGINATED_VEHICLES';
export const GET_VEHICLE_DATA = 'GET_VEHICLE_DATA';
export const ADD_FRANCHISE_REQUEST = 'ADD_FRANCHISE_REQUEST';

export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const GET_LOCATION_DATA = "GET_LOCATION_DATA";
export const HOMEPAGE_LOAD = "HOMEPAGE_LOAD";
export const CHANGE_CITY = "CHANGE_CITY";

export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";

export const BLOG_LIST = "BLOG_LIST"; 
export const BLOG_BY_ID = "BLOG_BY_ID"; 
